import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

// 최상위 폴더에 있는 layout.tsx는 공통 UI를 정의하는 역할. 모든 페이지에 적용됨.
// 차상위 폴더의 하위 폴더에 있는 layout.tsx는 그 폴더와 하위 페이지에 자동 적용되며 상위에 있는 layout도 포함함ㅁ

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar">
          {/* cmd + . 사용하면 import 창 나옴 */}
          <Link href="/">Home</Link>
          <Link href="/list">List</Link>
          <Link href="/cart">Cart</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
